	ORG $2000
	JMP BOOT_START

; ==============================================================================
; ZÁKLADNÍ DATA & TEXTY
; Umístěno na začátek paměti, aby ANTIC čip nikdy nepřekročil 1K/4K hardwarovou hranici!
; ==============================================================================
INTRO_DL
	dta b($70,$70,$70,$70,$70)
	dta b($42),a(TXT_TITLE)
	dta b($70,$70,$70)
	dta b($42),a(TXT_HISCR)
	dta b($70,$70,$70)
	dta b($42),a(TXT_START)
	dta b($70,$70,$70,$70)
	dta b($42),a(TXT_CREDIT)
	dta b($41),a(INTRO_DL)

DL_LOSE
	dta b($70,$70,$70,$70)
	dta b($42),a(TXT_LOSE)
	dta b($70)
	dta b($42),a(TXT_LOSE2)
	dta b($70,$70,$70,$70,$70,$70,$70)
	dta b($42),a(TXT_START)
	dta b($41),a(DL_LOSE)

DL_WIN
	dta b($70,$70,$70,$70)
	dta b($42),a(TXT_WIN1)
	dta b($70)
	dta b($42),a(TXT_WIN2)
	dta b($70,$70,$70,$70,$70,$70,$70)
	dta b($42),a(TXT_START)
	dta b($41),a(DL_WIN)

DL_HISCORE
	dta b($70,$70,$70,$70,$70,$70)
	dta b($42),a(TXT_NEW_HI)
	dta b($70,$70,$70)
	dta b($42),a(TXT_ENTER)
	dta b($70,$70,$70)
	dta b($42),a(TXT_CHARS)
	dta b($41),a(DL_HISCORE)

TXT_TITLE  dta d'          PITSTOP KITT REMASTER         '
TXT_HISCR  dta d'         HIGH SCORE: 000   AAA          '
TXT_START  dta d'              PRESS START               '
TXT_CREDIT dta d'              (C) N&P 2026              '
TXT_LOSE   dta d'           CRASHED! GAME OVER           '
TXT_LOSE2  dta d'         ENEMIES DESTROYED: 000         '
TXT_WIN1   dta d'        YOU ARE KNIGHT RIDER !!!        '
TXT_WIN2   dta d'         ENEMIES DESTROYED: 000         '
TXT_NEW_HI dta d'         *** NEW HIGH SCORE! *** '
TXT_ENTER  dta d'          ENTER YOUR INITIALS:          '
TXT_CHARS  dta d'                  A A A                 '

; --- SYSTÉMOVÉ ADRESY & POKEY ---
SAVMSC=$58 \ SAVMSH=$59 \ RTCLOK=$14 \ PORTA=$D300 \ TRIG0=$D010 \ GRACTL=$D01D \ PMBASE_REG=$D407
HPOSP0=$D000 \ HPOSP1=$D001 \ HPOSP2=$D002 \ HPOSP3=$D003 \ HPOSM0=$D004 \ HPOSM1=$D005 \ HPOSM2=$D006 \ HPOSM3=$D007
SIZEP0=$D008 \ SIZEP1=$D009 \ SIZEP2=$D00A \ SIZEP3=$D00B \ SIZEM=$D00C \ HITCLR=$D01E \ SDMCTL=$022F \ GPRIOR=$026F
PCOLR0=$02C0 \ PCOLR1=$02C1 \ PCOLR2=$02C2 \ PCOLR3=$02C3 \ AUDCTL=$D208
AUDF1=$D200 \ AUDC1=$D201 \ AUDF2=$D202 \ AUDC2=$D203 \ AUDF3=$D204 \ AUDC3=$D205 \ AUDF4=$D206 \ AUDC4=$D207
DMACTL=$D400 \ DLIST=$D402 \ GRAFP0=$D00D \ GRAFP1=$D00E \ GRAFP2=$D00F \ GRAFP3=$D010 \ GRAFM=$D011
VCOUNT=$D40B \ WSYNC=$D40A \ CONSOL=$D01F \ NMIEN=$D40E \ RANDOM=$D20A
COLP0=$D012 \ COLP1=$D013 \ COLP2=$D014 \ COLP3=$D015
CHBASE=$D409 \ COLBK=$D01A \ COLPF1=$D017 \ COLPF2=$D018
SDLSTL=$0230 \ SDLSTH=$0231 ; ZÁCHRANNÉ STÍNOVÉ REGISTRY PRO VBI!

; --- PROMĚNNÉ ---
SCR_LO=$80 \ SCR_HI=$81 \ ROW_CNT=$82 \ PIX_CEN=$83 \ PIX_HALF_W=$84 \ L_PIX=$85 \ R_PIX=$86 \ L_BYTE=$87 \ R_BYTE=$88
DISTANCE=$89 \ WIDEN_ACC=$8A \ TRACK_X=$8B \ HORIZON=$8C \ SIN_PTR=$8D \ BULLET_Y=$8E \ JUMP_VAL=$8F \ JUMP_DIR=$90
XSAVE=$91 \ JUMP_TIMER=$92 \ FIRE_SND_T=$93 \ SONG_PTR=$94 \ SONG_TICK=$95 \ CAR_FRAME=$96 \ TEMP_Y=$97
OPP_Y=$98 \ OPP_X=$99 \ OPP_SCR_LO=$9A \ OPP_SCR_HI=$9B \ OPP_LANE=$9C \ OPP_CUR_Y=$9D
HOLE_Y=$9E \ HOLE_LANE=$9F \ SKID_T=$A0 \ HOLE_X=$A1 \ HOLE_WAIT=$B1
END_S_LO=$9E \ END_S_HI=$9F ; Znovupoužití adres na konci hry pro pointery hudby
OPP2_Y=$A2 \ OPP2_X=$A3 \ OPP2_LANE=$A4 \ OPP2_CUR_Y=$A5 \ OPP_WAIT=$A6 \ OPP2_WAIT=$A7
EXP_SND_T=$A8 \ OPP_EXP_T=$AB \ OPP2_EXP_T=$AF \ PLAYER_EXP_T=$B0 \ TICK_50=$AC \ SEC_COUNT=$AD \ CUR_LEVEL=$AE
MOMENTUM=$B4 \ TREE_Y=$B5 \ TREE_WAIT=$B6 \ TREE_SIDE=$B7 \ TREE_X=$B8
TREE2_Y=$B9 \ TREE2_WAIT=$BA \ TREE2_SIDE=$BB \ TREE2_X=$BC
SCORE=$BD
HI_SCORE=$BE \ CURSOR_POS=$BF \ JOY_DELAY=$C0
SCORE_HI=$C1 \ HI_SCORE_HI=$C2

; Aliasy proměnných pro INTRO
SCAN_X=$80 \ SCAN_DIR=$81 \ VOLUME=$82

; ==============================================================================
; STUDENÝ START HRY
; ==============================================================================
BOOT_START
	LDA #0 \ STA HI_SCORE \ STA HI_SCORE_HI
	; Vytvoříme defaultní prázdné High Score
	JMP INTRO_START

; ==============================================================================
; INTRO SEKVENCE A TITULNÍ OBRAZOVKA
; ==============================================================================
INTRO_START
	SEI
	LDA #0 \ STA NMIEN \ STA AUDCTL \ STA SONG_PTR \ STA SONG_TICK
	STA DMACTL \ STA SDMCTL
	STA GRAFM \ STA HPOSM0 \ STA HITCLR
	
	STA SIZEP0 \ STA SIZEP1 \ STA SIZEP2 \ STA SIZEP3 \ STA SIZEM
	
	LDA #$40 \ STA PMBASE_REG
	STA $05 \ LDA #0 \ STA $04 \ TAY \ TAX
_I_PM_ZERO
	STA ($04),Y \ INY \ BNE _I_PM_ZERO \ INC $05 \ INX \ CPX #4 \ BNE _I_PM_ZERO

	LDY #40 \ LDA #$FF
_I_DRAW_EYE
	STA $4200,Y \ STA $4280,Y \ STA $4300,Y \ STA $4380,Y
	INY \ CPY #48 \ BNE _I_DRAW_EYE
	
	LDA #<INTRO_DL \ STA SDLSTL \ STA DLIST \ LDA #>INTRO_DL \ STA SDLSTH \ STA DLIST+1
	
	LDA #$2E \ STA DMACTL \ STA SDMCTL
	LDA #3 \ STA GRACTL
	
	LDA #$3E \ STA COLP0 \ LDA #$38 \ STA COLP1 \ LDA #$34 \ STA COLP2 \ LDA #$32 \ STA COLP3
	
	LDA #$E0 \ STA CHBASE
	LDA #$0F \ STA COLPF1 
	LDA #$00 \ STA COLBK \ STA COLPF2

	LDA #128 \ STA SCAN_X \ LDA #1 \ STA SCAN_DIR

INTRO_LOOP
	LDA VCOUNT \ BNE INTRO_LOOP
	LDA CONSOL \ AND #1 \ BNE _CHK_DONE \ JMP START_TRANSITION
_CHK_DONE

	LDA SONG_TICK \ BEQ I_NEXT_NOTE \ DEC SONG_TICK \ JMP I_SND_BREATH
I_NEXT_NOTE
	LDA #4 \ STA SONG_TICK \ LDX SONG_PTR \ LDA SONG_TAB,X \ STA AUDF4
	BEQ I_MUTE_NOTE \ LDA #$A6 \ STA AUDC4 \ JMP I_DONE_NOTE
I_MUTE_NOTE
	LDA #0 \ STA AUDC4
I_DONE_NOTE
	INC SONG_PTR \ LDA SONG_PTR \ CMP #32 \ BNE I_SND_BREATH \ LDA #0 \ STA SONG_PTR

I_SND_BREATH
	LDA SCAN_X \ SEC \ SBC #128 \ BPL I_POS_VAL \ EOR #$FF \ CLC \ ADC #1
I_POS_VAL
	LSR \ STA VOLUME
	; OPRAVENÝ ÚTLUM ZVUKU PRO ŠIRŠÍ SCANNER
	LDA #15 \ SEC \ SBC VOLUME \ BMI I_MUTE_B \ ORA #$A0 \ STA AUDC1 \ LDA #220 \ STA AUDF1
	LDA #13 \ SEC \ SBC VOLUME \ BMI I_MUTE_B \ ORA #$A0 \ STA AUDC2 \ LDA #225 \ STA AUDF2 \ JMP I_MOVE_KITT
I_MUTE_B
	LDA #0 \ STA AUDC1 \ STA AUDC2

I_MOVE_KITT
	LDA SCAN_X \ CLC \ ADC SCAN_DIR \ STA SCAN_X
	; OPRAVENÝ ROZSAH OKA (Dříve 100-156, Nyní 86-170)
	LDA SCAN_X \ CMP #170 \ BCC I_CH_L \ LDA #255 \ STA SCAN_DIR \ JMP I_UPD_POS
I_CH_L
	CMP #86 \ BCS I_UPD_POS \ LDA #1 \ STA SCAN_DIR

I_UPD_POS
	LDA SCAN_X \ STA HPOSP0 \ LDA SCAN_DIR \ CMP #1 \ BEQ I_MOVE_R
	LDA SCAN_X \ CLC \ ADC #3 \ STA HPOSP1 \ ADC #3 \ STA HPOSP2 \ ADC #3 \ STA HPOSP3 \ JMP I_WAIT_FRAME
I_MOVE_R
	LDA SCAN_X \ SEC \ SBC #3 \ STA HPOSP1 \ SBC #3 \ STA HPOSP2 \ SBC #3 \ STA HPOSP3

I_WAIT_FRAME
	LDA VCOUNT 
	CMP #60 
	BCC I_WAIT_FRAME
	JMP INTRO_LOOP

; --- PŘECHOD Z INTRA DO HRY ---
START_TRANSITION
	LDA #0 \ STA AUDCTL \ STA AUDC1 \ STA AUDC2 \ STA AUDC3 \ STA AUDC4
	STA GRACTL \ STA DMACTL \ STA SDMCTL
	LDA #$40 \ STA NMIEN
	CLI
	JMP GAME_START

; ==============================================================================
; HLAVNÍ HRA
; ==============================================================================
GAME_START
	LDA #7 \ JSR $EF9C
	
	LDA #$04 \ STA $02C8 \ LDA #$C4 \ STA $02C4 \ LDA #$0F \ STA $02C5 \ LDA #$76 \ STA $02C6 
	LDA #$40 \ STA PMBASE_REG \ LDA #$2E \ STA SDMCTL \ LDA #$03 \ STA GRACTL \ LDA #$01 \ STA GPRIOR 
	LDA #0 \ STA SIZEP0 \ STA SIZEP1 \ STA SIZEP2 \ STA SIZEP3 \ LDA #$F0 \ STA SIZEM 
	LDA #$34 \ STA PCOLR0 \ STA PCOLR1 \ LDA #$00 \ STA PCOLR2 \ STA PCOLR3 
	
	LDA #$40 \ STA $05 \ LDA #0 \ STA $04 \ TAY \ TAX
PM_ZERO
	STA ($04),Y \ INY \ BNE PM_ZERO \ INC $05 \ INX \ CPX #8 \ BNE PM_ZERO

	LDA #50 \ STA TICK_50 \ LDA #0 \ STA SEC_COUNT \ STA CUR_LEVEL \ STA OPP_EXP_T \ STA OPP2_EXP_T \ STA PLAYER_EXP_T \ STA MOMENTUM
	STA AUDCTL \ STA AUDC1 \ STA AUDC2 \ STA AUDC3 \ STA AUDC4 \ STA $D205
	STA BULLET_Y \ STA JUMP_VAL \ STA JUMP_DIR \ STA SONG_PTR \ STA SONG_TICK
	STA SKID_T \ STA EXP_SND_T \ STA OPP_Y \ STA OPP2_Y \ STA SCORE \ STA SCORE_HI
	LDA #120 \ STA HPOSP0 \ STA HPOSP2 \ LDA #128 \ STA HPOSP1 \ STA HPOSP3
	
	LDA #80 \ STA TRACK_X \ LDA #42 \ STA HOLE_Y \ LDA #50 \ STA OPP_WAIT \ LDA #150 \ STA OPP2_WAIT \ LDA #15 \ STA HOLE_WAIT
	LDA #5 \ STA TREE_WAIT \ LDA #0 \ STA TREE_Y
	LDA #15 \ STA TREE2_WAIT \ LDA #0 \ STA TREE2_Y

MAIN_LOOP
	DEC TICK_50 \ BEQ _DO_TICK \ JMP _SKIP_CYCLE
_DO_TICK
	LDA #50 \ STA TICK_50 \ INC SEC_COUNT \ LDA SEC_COUNT \ CMP #15 \ BEQ _DO_LVL \ JMP _SKIP_CYCLE
_DO_LVL
	LDA #0 \ STA SEC_COUNT
	
	INC CUR_LEVEL \ LDA CUR_LEVEL \ CMP #10 \ BNE _UPD_COLORS
	JMP GO_WIN_SEQ ; <--- VÍTĚZSTVÍ AŽ PO 10. LEVELU!

; --- STRUKTURA BAREV PRO 10 LEVELŮ ---
_UPD_COLORS
	LDA CUR_LEVEL
	CMP #0 \ BNE _CHK_L1
	; L1: DEN
	LDA #$04 \ STA $02C8 \ LDA #$C4 \ STA $02C4 \ LDA #$0F \ STA $02C5 \ LDA #$76 \ STA $02C6 \ JMP _SKIP_CYCLE
_CHK_L1
	CMP #1 \ BNE _CHK_L2
	; L2: NOC
	LDA #$04 \ STA $02C8 \ LDA #$C4 \ STA $02C4 \ LDA #$0F \ STA $02C5 \ LDA #$00 \ STA $02C6 \ JMP _SKIP_CYCLE
_CHK_L2
	CMP #2 \ BNE _CHK_L3
	; L3: ZIMA
	LDA #$0E \ STA $02C8 \ LDA #$B8 \ STA $02C4 \ LDA #$00 \ STA $02C5 \ LDA #$76 \ STA $02C6 \ JMP _SKIP_CYCLE
_CHK_L3
	CMP #3 \ BNE _CHK_L4
	; L4: ZIMNI MESTO
	LDA #$0E \ STA $02C8 \ LDA #$C4 \ STA $02C4 \ LDA #$00 \ STA $02C5 \ LDA #$76 \ STA $02C6 \ JMP _SKIP_CYCLE
_CHK_L4
	CMP #4 \ BNE _CHK_L5
	; L5: NEVADSKA POUST
	LDA #$24 \ STA $02C8 \ LDA #$16 \ STA $02C4 \ LDA #$0F \ STA $02C5 \ LDA #$22 \ STA $02C6 \ JMP _SKIP_CYCLE
_CHK_L5
	CMP #5 \ BNE _CHK_L6
	; L6: NEON SUNSET CITY
	LDA #$64 \ STA $02C8 \ LDA #$22 \ STA $02C4 \ LDA #$00 \ STA $02C5 \ LDA #$46 \ STA $02C6 \ JMP _SKIP_CYCLE
_CHK_L6
	CMP #6 \ BNE _CHK_L7
	; L7: BLOOD CANYON
	LDA #$42 \ STA $02C8 \ LDA #$46 \ STA $02C4 \ LDA #$00 \ STA $02C5 \ LDA #$44 \ STA $02C6 \ JMP _SKIP_CYCLE
_CHK_L7
	CMP #7 \ BNE _CHK_L8
	; L8: MIDNIGHT BLIZZARD (Noční ledovec)
	LDA #$84 \ STA $02C8 \ LDA #$74 \ STA $02C4 \ LDA #$0F \ STA $02C5 \ LDA #$82 \ STA $02C6 \ JMP _SKIP_CYCLE
_CHK_L8
	CMP #8 \ BNE _SET_LVL10
	; L9: GOLDEN DAWN (Zlatý úsvit)
	LDA #$1A \ STA $02C8 \ LDA #$16 \ STA $02C4 \ LDA #$00 \ STA $02C5 \ LDA #$12 \ STA $02C6 \ JMP _SKIP_CYCLE
_SET_LVL10
	; L10: CYBERPUNK ABYSS
	LDA #$A4 \ STA $02C8 \ LDA #$D4 \ STA $02C4 \ LDA #$0F \ STA $02C5 \ LDA #$C2 \ STA $02C6 

_SKIP_CYCLE
	; PLYNULÝ FÁZOVÝ AKUMULÁTOR PRO ZRYCHLOVÁNÍ HUDBY
	LDX CUR_LEVEL
	LDA SONG_TICK
	CLC
	ADC MUSIC_SPEED,X
	STA SONG_TICK
	BCC SND_ENGINE ; Pokud nepřeteče paměť, přeskoč notu
NEXT_NOTE
	LDX SONG_PTR \ LDA SONG_TAB,X \ STA AUDF4
	BEQ MUTE_NOTE \ LDA #$A8 \ STA AUDC4 \ JMP DONE_NOTE
MUTE_NOTE
	LDA #0 \ STA AUDC4
DONE_NOTE
	INC SONG_PTR \ LDA SONG_PTR \ CMP #32 \ BNE SND_ENGINE \ LDA #0 \ STA SONG_PTR

SND_ENGINE
	LDA #0 \ STA AUDC2 
	LDA EXP_SND_T \ BEQ _NO_EXP \ DEC EXP_SND_T \ LDA EXP_SND_T \ ASL \ ASL \ STA AUDF3 \ LDA #$88 \ STA AUDC3 \ JMP _SHOOT_SND
_NO_EXP
	LDA #0 \ STA AUDC3

_SHOOT_SND
	LDA TRIG0 \ BNE NO_FIRE \ LDA BULLET_Y \ BNE NO_FIRE
	LDA #102 \ SEC \ SBC JUMP_VAL \ STA BULLET_Y \ LDA #124 \ STA HPOSM0 \ LDA #10 \ STA FIRE_SND_T \ LDA #$A8 \ STA AUDC1
NO_FIRE
	LDA FIRE_SND_T \ BEQ SND_F_OFF \ DEC FIRE_SND_T \ LDA FIRE_SND_T \ CLC \ ADC #$A0 \ STA AUDC1
	LDA FIRE_SND_T \ ASL \ STA AUDF1 \ JMP CHK_JOY
SND_F_OFF
	LDA SKID_T \ BNE CHK_JOY \ LDA #0 \ STA AUDC1

; ==============================================================================
; ZATÁČENÍ A FYZIKA
; ==============================================================================
CHK_JOY
	LDA JUMP_VAL \ CMP #2 \ BCS _SKIP_SKID \ LDA $D00A \ ORA $D00B \ AND #$03 \ BEQ _SKIP_SKID \ LDA #30 \ STA SKID_T
_SKIP_SKID
	STA HITCLR \ LDA SKID_T \ BEQ _NORMAL_JOY \ DEC SKID_T
	LDA #$A2 \ STA AUDC1 \ LDA #40 \ STA AUDF1 \ LDA RTCLOK \ AND #$02 \ BNE _SK_R \ LDA #16 \ BNE _SK_D
_SK_R
	LDA #32
_SK_D
	STA CAR_FRAME \ JMP _NO_JOY 

_NORMAL_JOY
	LDA #0 \ STA CAR_FRAME 
	LDA PORTA \ AND #$04 \ BNE CHK_R 
	LDA #16 \ STA CAR_FRAME 
	
	; KONTROLA LEDOVÝCH LEVELŮ (2=Zima, 3=Zimni mesto, 7=Midnight Blizzard)
	LDA CUR_LEVEL \ CMP #2 \ BEQ _IS_ICE \ CMP #3 \ BEQ _IS_ICE \ CMP #7 \ BEQ _IS_ICE
	JMP _L_NORMAL
_IS_ICE
	LDA MOMENTUM \ CMP #7 \ BEQ _UPDATE_X   
	INC MOMENTUM \ JMP _UPDATE_X
_L_NORMAL
	LDA TRACK_X \ CMP #110 \ BCC _DO_INC_L \ JMP J_D
_DO_INC_L
	INC TRACK_X \ INC TRACK_X \ JMP J_D

CHK_R
	LDA PORTA \ AND #$08 \ BNE _NO_JOY 
	LDA #32 \ STA CAR_FRAME 
	
	LDA CUR_LEVEL \ CMP #2 \ BEQ _IS_ICE_R \ CMP #3 \ BEQ _IS_ICE_R \ CMP #7 \ BEQ _IS_ICE_R
	JMP _R_NORMAL
_IS_ICE_R
	LDA MOMENTUM \ CMP #$F9 \ BEQ _UPDATE_X 
	DEC MOMENTUM \ JMP _UPDATE_X
_R_NORMAL
	LDA TRACK_X \ CMP #54 \ BCS _DO_DEC_R \ JMP J_D
_DO_DEC_R
	DEC TRACK_X \ DEC TRACK_X \ JMP J_D

_NO_JOY
	LDA CUR_LEVEL \ CMP #2 \ BEQ _ICE_NO_JOY \ CMP #3 \ BEQ _ICE_NO_JOY \ CMP #7 \ BEQ _ICE_NO_JOY
	JMP J_D
_ICE_NO_JOY
	LDA MOMENTUM \ BNE _DO_MOMENTUM_DEC
	JMP _UPDATE_X
_DO_MOMENTUM_DEC
	LDA RTCLOK \ AND #1 \ BEQ _UPDATE_X 
	
	LDA MOMENTUM
	BMI _DEC_MOM
	DEC MOMENTUM \ JMP _UPDATE_X
_DEC_MOM
	INC MOMENTUM

_UPDATE_X
	LDA MOMENTUM \ BNE _DO_UPD_X
	JMP J_D
_DO_UPD_X
	CLC \ ADC TRACK_X
	CMP #54 \ BCC _LIMIT_R
	CMP #110 \ BCS _LIMIT_L
	STA TRACK_X \ JMP J_D
_LIMIT_R
	LDA #54 \ STA TRACK_X \ LDA #0 \ STA MOMENTUM \ JMP J_D
_LIMIT_L
	LDA #110 \ STA TRACK_X \ LDA #0 \ STA MOMENTUM

J_D
	LDA BULLET_Y \ BEQ JUMP_LOGIC \ TAY \ LDA $4180,Y \ AND #$FC \ STA $4180,Y 
	LDA BULLET_Y \ SEC \ SBC #4 \ STA BULLET_Y \ CMP #24 \ BCC B_OFF 
	TAY \ LDA $4180,Y \ ORA #$03 \ STA $4180,Y \ JMP JUMP_LOGIC 
B_OFF
	LDA #0 \ STA BULLET_Y

JUMP_LOGIC
	LDA JUMP_DIR \ BNE J_ACT \ LDA PORTA \ AND #$02 \ BNE DRAW_PHASE \ LDA #1 \ STA JUMP_DIR \ JMP DRAW_PHASE
J_ACT
	CMP #1 \ BEQ J_UP \ CMP #3 \ BEQ J_HANG
J_DWN
	DEC JUMP_VAL \ LDA JUMP_VAL \ BNE J_S_U \ STA JUMP_DIR \ LDA #0 \ STA AUDC2 \ JMP DRAW_PHASE
J_UP
	INC JUMP_VAL \ LDA JUMP_VAL \ CMP #12 \ BCC J_S_U \ LDA #3 \ STA JUMP_DIR \ LDA #12 \ STA JUMP_TIMER \ JMP J_S_U
J_HANG
	DEC JUMP_TIMER \ BNE J_S_U \ LDA #2 \ STA JUMP_DIR
J_S_U
	LDA #$A2 \ STA AUDC2 \ LDA JUMP_VAL \ EOR #$FF \ STA AUDF2

DRAW_PHASE
	LDY #16 \ LDA #0 
C_CLR
	STA $4200,Y \ STA $4280,Y \ STA $4300,Y \ STA $4380,Y \ INY \ CPY #128 \ BNE C_CLR
	LDA #96 \ SEC \ SBC JUMP_VAL \ TAY \ STY TEMP_Y \ CLC \ LDA TEMP_Y \ ADC #16 \ STA TEMP_Y 
	
	LDX CAR_FRAME 
D_CAR
	LDA CAR_LEFT,X \ STA $4200,Y \ LDA CAR_RIGHT,X \ STA $4280,Y \ LDA TIRE_LEFT,X \ STA $4300,Y \ LDA TIRE_RIGHT,X \ STA $4380,Y
	INY \ INX \ CPY TEMP_Y \ BNE D_CAR

_D_DONE
	LDX SIN_PTR \ LDA SIN_TAB,X \ STA HORIZON \ INC SIN_PTR \ LDA SIN_PTR \ CMP #48 \ BNE S_R \ LDA #0 \ STA SIN_PTR
S_R
	LDA SAVMSC \ STA SCR_LO \ LDA SAVMSH \ STA SCR_HI 

S_H
	LDX HORIZON
S_ROW
	STX XSAVE \ CPX #13 \ BCS _DO_SKY_BRANCH \ JMP _DRAW_LANDSCAPE 
_DO_SKY_BRANCH
	LDY #39 \ LDA #$FF
_S_FILL
	STA (SCR_LO),Y \ DEY \ BPL _S_FILL
	
	LDA CUR_LEVEL \ BEQ _S_NXT_JMP
	LDX XSAVE \ LDA RTCLOK \ AND #$10 \ STA TEMP_Y 
	
	CPX #25 \ BNE _SKIP_ST1 \ JMP _ST1
_SKIP_ST1
	CPX #22 \ BNE _SKIP_ST2 \ JMP _ST2
_SKIP_ST2
	CPX #19 \ BNE _SKIP_ST3 \ JMP _ST3
_SKIP_ST3
	CPX #16 \ BNE _SKIP_ST4 \ JMP _ST4
_SKIP_ST4
	CPX #14 \ BNE _S_NXT_JMP \ JMP _ST5

_S_NXT_JMP
	JMP _S_NXT

_ST1
	LDA TEMP_Y \ BNE _S1_B 
	LDY #3 \ LDA CUR_LEVEL \ CMP #2 \ BCS _W1A \ LDA #$BF \ BNE _W1B 
_W1A	LDA #$3F 
_W1B	STA (SCR_LO),Y 
_S1_B
	LDA TEMP_Y \ BEQ _S1_E 
	LDY #32 \ LDA CUR_LEVEL \ CMP #2 \ BCS _W1C \ LDA #$FB \ BNE _W1D 
_W1C	LDA #$F3 
_W1D	STA (SCR_LO),Y 
_S1_E
	JMP _S_NXT

_ST2
	LDA TEMP_Y \ BNE _S2_B 
	LDY #10 \ LDA CUR_LEVEL \ CMP #2 \ BCS _W2A \ LDA #$EF \ BNE _W2B 
_W2A	LDA #$CF 
_W2B	STA (SCR_LO),Y 
_S2_B
	LDA TEMP_Y \ BEQ _S2_E 
	LDY #25 \ LDA CUR_LEVEL \ CMP #2 \ BCS _W2C \ LDA #$FE \ BNE _W2D 
_W2C	LDA #$FC 
_W2D	STA (SCR_LO),Y 
_S2_E
	JMP _S_NXT

_ST3
	LDA TEMP_Y \ BNE _S3_B 
	LDY #2 \ LDA CUR_LEVEL \ CMP #2 \ BCS _W3A \ LDA #$BF \ BNE _W3B 
_W3A	LDA #$3F 
_W3B	STA (SCR_LO),Y 
_S3_B
	LDA TEMP_Y \ BEQ _S3_E 
	LDY #18 \ LDA CUR_LEVEL \ CMP #2 \ BCS _W3C \ LDA #$FB \ BNE _W3D 
_W3C	LDA #$F3 
_W3D	STA (SCR_LO),Y 
_S3_E
	JMP _S_NXT

_ST4
	LDA TEMP_Y \ BNE _S4_B 
	LDY #24 \ LDA CUR_LEVEL \ CMP #2 \ BCS _W4A \ LDA #$EF \ BNE _W4B 
_W4A	LDA #$CF 
_W4B	STA (SCR_LO),Y 
_S4_B
	LDA TEMP_Y \ BEQ _S4_E 
	LDY #38 \ LDA CUR_LEVEL \ CMP #2 \ BCS _W4C \ LDA #$FE \ BNE _W4D 
_W4C	LDA #$FC 
_W4D	STA (SCR_LO),Y 
_S4_E
	JMP _S_NXT

_ST5
	LDA TEMP_Y \ BNE _S5_B 
	LDY #8 \ LDA CUR_LEVEL \ CMP #2 \ BCS _W5A \ LDA #$BF \ BNE _W5B 
_W5A	LDA #$3F 
_W5B	STA (SCR_LO),Y 
_S5_B
	LDA TEMP_Y \ BEQ _S5_E 
	LDY #31 \ LDA CUR_LEVEL \ CMP #2 \ BCS _W5C \ LDA #$FB \ BNE _W5D 
_W5C	LDA #$F3 
_W5D	STA (SCR_LO),Y 
_S5_E
	JMP _S_NXT

; --- BEZPEČNÁ DISTRIBUCE GRAFIKY KOPCŮ/MĚSTA/ZIMY PRO 10 LEVELŮ ---
_DRAW_LANDSCAPE
	LDA CUR_LEVEL
	CMP #0 \ BEQ _DO_DAY
	CMP #4 \ BEQ _DO_DAY
	CMP #6 \ BEQ _DO_DAY
	CMP #8 \ BEQ _DO_DAY
	CMP #2 \ BEQ _DO_WINTER
	CMP #7 \ BEQ _DO_WINTER
_DO_CITY
	LDA CITY_LO-1,X \ STA $04 \ LDA CITY_HI-1,X \ STA $05 \ JMP _C_FILL_M
_DO_DAY
	LDA HILLS_LO-1,X \ STA $04 \ LDA HILLS_HI-1,X \ STA $05 \ JMP _C_FILL_M
_DO_WINTER
	LDA WINTER_LO-1,X \ STA $04 \ LDA WINTER_HI-1,X \ STA $05
_C_FILL_M
	LDY #39
_C_FILL
	LDA ($04),Y \ STA (SCR_LO),Y \ DEY \ BPL _C_FILL
_S_NXT
	CLC \ LDA SCR_LO \ ADC #40 \ STA SCR_LO \ BCC S_N \ INC SCR_HI
S_N
	LDX XSAVE \ DEX \ BEQ S_DONE_JMP \ JMP S_ROW
S_DONE_JMP
	JMP S_DONE
S_DONE
	; --- ZRYCHLOVÁNÍ SILNICE PŘES ČTVRTINOVOU FUNKCI ---
	JSR CALC_SPEED
	CLC \ ADC DISTANCE \ STA DISTANCE 
	LDA #96 \ SEC \ SBC HORIZON \ STA ROW_CNT
	LDA TRACK_X \ STA PIX_CEN \ LDA #14 \ STA PIX_HALF_W \ LDA #0 \ STA WIDEN_ACC

DRAW_ROAD_LOOP
	LDA PIX_CEN \ SEC \ SBC PIX_HALF_W \ BCS OK_L \ LDA #$FF \ STA L_PIX \ LDA #0 \ STA L_BYTE \ BEQ _CR_CHK
OK_L
	STA L_PIX \ LSR \ LSR \ STA L_BYTE
_CR_CHK
	LDA PIX_CEN \ CLC \ ADC PIX_HALF_W \ BCS CL_R \ CMP #159 \ BCC OK_R
CL_R
	LDA #$FF \ STA R_PIX \ LDA #40 \ STA R_BYTE \ BNE _DRAW_ST
OK_R
	STA R_PIX \ LSR \ LSR \ STA R_BYTE
_DRAW_ST
	LDA L_PIX \ CMP #$FF \ BEQ SKP_LCURB \ LDY #0 \ CPY L_BYTE \ BCS D_GL \ LDA #$55
G_L
	STA (SCR_LO),Y \ INY \ CPY L_BYTE \ BCC G_L
D_GL
	LDY L_BYTE \ CLC \ LDA ROW_CNT \ ADC DISTANCE \ AND #$04 \ BNE K_L_B
	LDA L_PIX \ AND #$03 \ TAX \ LDA MASK_L_WHITE,X \ JMP D_L
K_L_B
	LDA L_PIX \ AND #$03 \ TAX \ LDA MASK_L_BLACK,X
D_L
	STA (SCR_LO),Y \ INY \ JMP _FILL_ROAD
SKP_LCURB
	LDY #0
_FILL_ROAD
	CPY R_BYTE \ BCS SKP_RCURB \ LDA #$00
A_L
	STA (SCR_LO),Y \ INY \ CPY R_BYTE \ BCC A_L
SKP_RCURB
	LDA R_PIX \ CMP #$FF \ BEQ SKP_RGRASS \ LDY R_BYTE \ CLC \ LDA ROW_CNT \ ADC DISTANCE \ AND #$04 \ BNE K_R_B
	LDA R_PIX \ AND #$03 \ TAX \ LDA MASK_R_WHITE,X \ JMP D_R
K_R_B
	LDA R_PIX \ AND #$03 \ TAX \ LDA MASK_R_BLACK,X
D_R
	STA (SCR_LO),Y \ INY
SKP_RGRASS
	CPY #40 \ BCS D_GR \ LDA #$55
G_R
	STA (SCR_LO),Y \ INY \ CPY #40 \ BCC G_R
D_GR
	CLC \ LDA SCR_LO \ ADC #40 \ STA SCR_LO \ BCC R_N \ INC SCR_HI
R_N
	CLC \ LDA WIDEN_ACC \ ADC #160 \ STA WIDEN_ACC \ BCC NO_W \ INC PIX_HALF_W
NO_W
	DEC ROW_CNT \ BEQ DONE \ JMP DRAW_ROAD_LOOP

DONE
	LDA RTCLOK
WAIT_S
	CMP RTCLOK \ BEQ WAIT_S \ JMP HOLE_ROUTINE

; ==============================================================================
; LOGIKA SKVRNY
; ==============================================================================
HOLE_ROUTINE
	LDA HOLE_Y \ BNE _H_LOGIC \ DEC HOLE_WAIT \ BEQ _H_SPAWN \ JMP _H_DONE 
_H_SPAWN
	LDA #22 \ STA HOLE_Y
	LDA RANDOM \ CMP #85 \ BCC _HL \ CMP #170 \ BCC _HC
	LDA #2 \ BNE _HS
_HL	LDA #0 \ BEQ _HS 
_HC	LDA #1
_HS	STA HOLE_LANE
	LDA RANDOM \ AND #$1F \ ORA #$10 \ STA HOLE_WAIT \ JMP _H_CALCX

_H_LOGIC
	JSR CALC_SPEED
	CLC \ ADC HOLE_Y \ STA HOLE_Y
	LDA HOLE_Y \ CMP #45 \ BCC _HS_D
	INC HOLE_Y \ LDA HOLE_Y \ CMP #75 \ BCC _HS_D \ INC HOLE_Y
_HS_D
	LDA HOLE_Y \ CMP #96 \ BCC _H_CALCX \ LDA #0 \ STA HOLE_Y \ JMP _H_DONE 
_H_CALCX
	LDA TRACK_X \ LSR \ LSR \ SEC \ SBC #1 \ STA HOLE_X
	LDA HOLE_LANE \ CMP #1 \ BEQ _H_X_DONE
	LDA HOLE_Y \ LSR \ LSR \ LSR \ STA TEMP_Y
	LDA HOLE_LANE \ CMP #0 \ BEQ _H_LEFT
_H_RIGHT
	LDA HOLE_X \ CLC \ ADC TEMP_Y \ STA HOLE_X \ JMP _H_X_DONE
_H_LEFT
	LDA HOLE_X \ SEC \ SBC TEMP_Y \ STA HOLE_X
_H_X_DONE

	LDA JUMP_VAL \ CMP #5 \ BCS _DRAW_HOLE 
	LDA HOLE_Y \ CMP #70 \ BCC _DRAW_HOLE 
	LDA HOLE_X \ CMP #14 \ BCC _DRAW_HOLE \ CMP #22 \ BCS _DRAW_HOLE 
	LDA SKID_T \ BNE _DRAW_HOLE 
	LDA #30 \ STA SKID_T 
_DRAW_HOLE
	LDA SAVMSC \ STA OPP_SCR_LO \ LDA SAVMSH \ STA OPP_SCR_HI
	LDX HOLE_Y \ BEQ _SKIP_MUL_H
_MUL_LOOP_H
	CLC \ LDA OPP_SCR_LO \ ADC #40 \ STA OPP_SCR_LO \ BCC _NO_C_H \ INC OPP_SCR_HI
_NO_C_H
	DEX \ BNE _MUL_LOOP_H
_SKIP_MUL_H
	CLC \ LDA OPP_SCR_LO \ ADC HOLE_X \ STA OPP_SCR_LO \ BCC _NO_C2_H \ INC OPP_SCR_HI
_NO_C2_H
	LDX #0 \ LDY #0
_D_LH
	LDA HOLE_S0,X \ ORA (OPP_SCR_LO),Y \ STA (OPP_SCR_LO),Y \ INY
	LDA HOLE_S1,X \ ORA (OPP_SCR_LO),Y \ STA (OPP_SCR_LO),Y \ INY
	LDA HOLE_S2,X \ ORA (OPP_SCR_LO),Y \ STA (OPP_SCR_LO),Y \ INY
	LDA HOLE_S3,X \ ORA (OPP_SCR_LO),Y \ STA (OPP_SCR_LO),Y \ DEY \ DEY \ DEY
	CLC \ LDA OPP_SCR_LO \ ADC #40 \ STA OPP_SCR_LO \ BCC _NC1_H \ INC OPP_SCR_HI
_NC1_H
	INX \ CPX #16 \ BNE _D_LH
_H_DONE
	JMP TREE_ROUTINE

; ==============================================================================
; LOGIKA STROMŮ
; ==============================================================================
TREE_ROUTINE
	LDA TREE_Y \ BNE _T_LOGIC \ DEC TREE_WAIT \ BEQ _T_SPAWN \ JMP _T_DONE
_T_SPAWN
	LDA #22 \ STA TREE_Y
	LDA RANDOM \ AND #1 \ STA TREE_SIDE
	LDA RANDOM \ AND #$0F \ ORA #$04 \ STA TREE_WAIT \ JMP _T_CALCX

_T_LOGIC
	JSR CALC_SPEED
	CLC \ ADC TREE_Y \ STA TREE_Y
	LDA TREE_Y \ CMP #45 \ BCC _TS_D 
	INC TREE_Y \ LDA TREE_Y \ CMP #75 \ BCC _TS_D \ INC TREE_Y
_TS_D
	LDA TREE_Y \ CMP #96 \ BCC _T_CALCX \ LDA #0 \ STA TREE_Y \ JMP _T_DONE 
_T_CALCX
	LDA TRACK_X \ LSR \ LSR \ STA TREE_X
	LDA TREE_Y \ SEC \ SBC #20 \ LSR \ LSR \ STA TEMP_Y 
	LDA TREE_SIDE \ BEQ _T_LEFT
_T_RIGHT
	LDA TREE_X \ CLC \ ADC TEMP_Y \ ADC #4 \ STA TREE_X \ JMP _T_X_DONE 
_T_LEFT
	LDA TREE_X \ SEC \ SBC TEMP_Y \ SBC #5 \ STA TREE_X
_T_X_DONE
	LDA TREE_X \ CMP #38 \ BCS _T_DONE 

_DRAW_TREE
	LDA SAVMSC \ STA OPP_SCR_LO \ LDA SAVMSH \ STA OPP_SCR_HI
	LDX TREE_Y \ BEQ _SKIP_MUL_T
_MUL_LOOP_T
	CLC \ LDA OPP_SCR_LO \ ADC #40 \ STA OPP_SCR_LO \ BCC _NO_C_T \ INC OPP_SCR_HI
_NO_C_T
	DEX \ BNE _MUL_LOOP_T
_SKIP_MUL_T
	CLC \ LDA OPP_SCR_LO \ ADC TREE_X \ STA OPP_SCR_LO \ BCC _NO_C2_T \ INC OPP_SCR_HI
_NO_C2_T
	LDX #0 \ LDY #0
_D_LT
	LDA TREE_S0,X \ EOR (OPP_SCR_LO),Y \ STA (OPP_SCR_LO),Y \ INY
	LDA TREE_S1,X \ EOR (OPP_SCR_LO),Y \ STA (OPP_SCR_LO),Y \ DEY
	CLC \ LDA OPP_SCR_LO \ ADC #40 \ STA OPP_SCR_LO \ BCC _NC1_T \ INC OPP_SCR_HI
_NC1_T
	INX \ CPX #8 \ BNE _D_LT
_T_DONE
	JMP TREE2_ROUTINE

TREE2_ROUTINE
	LDA TREE2_Y \ BNE _T2_LOGIC \ DEC TREE2_WAIT \ BEQ _T2_SPAWN \ JMP _T2_DONE
_T2_SPAWN
	LDA #22 \ STA TREE2_Y
	LDA RANDOM \ AND #1 \ STA TREE2_SIDE
	LDA RANDOM \ AND #$0F \ ORA #$08 \ STA TREE2_WAIT \ JMP _T2_CALCX

_T2_LOGIC
	JSR CALC_SPEED
	CLC \ ADC TREE2_Y \ STA TREE2_Y
	LDA TREE2_Y \ CMP #45 \ BCC _T2S_D 
	INC TREE2_Y \ LDA TREE2_Y \ CMP #75 \ BCC _T2S_D \ INC TREE2_Y
_T2S_D
	LDA TREE2_Y \ CMP #96 \ BCC _T2_CALCX \ LDA #0 \ STA TREE2_Y \ JMP _T2_DONE 
_T2_CALCX
	LDA TRACK_X \ LSR \ LSR \ STA TREE2_X
	LDA TREE2_Y \ SEC \ SBC #20 \ LSR \ LSR \ STA TEMP_Y 
	LDA TREE2_SIDE \ BEQ _T2_LEFT
_T2_RIGHT
	LDA TREE2_X \ CLC \ ADC TEMP_Y \ ADC #4 \ STA TREE2_X \ JMP _T2_X_DONE 
_T2_LEFT
	LDA TREE2_X \ SEC \ SBC TEMP_Y \ SBC #5 \ STA TREE2_X
_T2_X_DONE
	LDA TREE2_X \ CMP #38 \ BCS _T2_DONE 

_DRAW_TREE2
	LDA SAVMSC \ STA OPP_SCR_LO \ LDA SAVMSH \ STA OPP_SCR_HI
	LDX TREE2_Y \ BEQ _SKIP_MUL_T2
_MUL_LOOP_T2
	CLC \ LDA OPP_SCR_LO \ ADC #40 \ STA OPP_SCR_LO \ BCC _NO_C_T2 \ INC OPP_SCR_HI
_NO_C_T2
	DEX \ BNE _MUL_LOOP_T2
_SKIP_MUL_T2
	CLC \ LDA OPP_SCR_LO \ ADC TREE2_X \ STA OPP_SCR_LO \ BCC _NO_C2_T2 \ INC OPP_SCR_HI
_NO_C2_T2
	LDX #0 \ LDY #0
_D_LT2
	LDA TREE_S0,X \ EOR (OPP_SCR_LO),Y \ STA (OPP_SCR_LO),Y \ INY
	LDA TREE_S1,X \ EOR (OPP_SCR_LO),Y \ STA (OPP_SCR_LO),Y \ DEY
	CLC \ LDA OPP_SCR_LO \ ADC #40 \ STA OPP_SCR_LO \ BCC _NC1_T2 \ INC OPP_SCR_HI
_NC1_T2
	INX \ CPX #8 \ BNE _D_LT2
_T2_DONE
	JMP OPP_ROUTINE

; ==============================================================================
; LOGIKA SOUPEŘŮ A SKÓROVÁNÍ (OPRAVENO NA 2-BYTE PRO 100+ BODO!)
; ==============================================================================
OPP_ROUTINE
	LDA OPP_Y \ BNE _O1_LOGIC \ DEC OPP_WAIT \ BEQ _O1_SPAWN \ JMP _O1_DONE 
_O1_SPAWN
	LDA #22 \ STA OPP_Y
	LDA RANDOM \ CMP #85 \ BCC _L1 \ CMP #170 \ BCC _C1
	LDA #2 \ BNE _S1
_L1	LDA #0 \ BEQ _S1 
_C1	LDA #1
_S1	STA OPP_LANE
	LDA RANDOM \ AND #$3F \ ORA #$20 \ STA OPP_WAIT \ JMP _O1_CALCX

_O1_LOGIC
	LDA OPP_EXP_T \ BEQ _O1_MOVE \ DEC OPP_EXP_T \ BNE _O1_CALCX
	LDA #0 \ STA OPP_Y \ JMP _O1_DONE 
_O1_MOVE
	JSR CALC_SPEED
	CLC \ ADC OPP_Y \ STA OPP_Y
	LDA OPP_Y \ CMP #45 \ BCC _S1_D 
	INC OPP_Y \ LDA OPP_Y \ CMP #75 \ BCC _S1_D \ INC OPP_Y
_S1_D
	LDA OPP_Y \ CMP #96 \ BCC _O1_CALCX \ LDA #0 \ STA OPP_Y \ JMP _O1_DONE 
_O1_CALCX
	LDA TRACK_X \ LSR \ LSR \ SEC \ SBC #1 \ STA OPP_X
	LDA OPP_LANE \ CMP #1 \ BEQ _O1_X_DONE
	LDA OPP_Y \ LSR \ LSR \ LSR \ STA TEMP_Y
	LDA OPP_LANE \ CMP #0 \ BEQ _O1_LEFT
_O1_RIGHT
	LDA OPP_X \ CLC \ ADC TEMP_Y \ STA OPP_X \ JMP _O1_X_DONE
_O1_LEFT
	LDA OPP_X \ SEC \ SBC TEMP_Y \ STA OPP_X
_O1_X_DONE

	LDA OPP_EXP_T \ BNE _O1_P_COL
	LDA BULLET_Y \ BEQ _O1_P_COL
	
	; ODPUŠTĚNÍ NÁRAZU (Rozšířený Hitbox) POUZE OD LEVELU 3
	SEC \ SBC OPP_Y
	LDX CUR_LEVEL \ CPX #2 \ BCS _O1_WIDE_HIT
_O1_NORM_HIT
	CMP #26 \ BCC _O1_P_COL \ CMP #34 \ BCS _O1_P_COL \ JMP _O1_X_CHK
_O1_WIDE_HIT
	CMP #22 \ BCC _O1_P_COL \ CMP #38 \ BCS _O1_P_COL
_O1_X_CHK
	LDA OPP_X \ CMP #15 \ BCC _O1_P_COL \ CMP #21 \ BCS _O1_P_COL
	
	; === TADY SE POČÍTÁ SKÓRE PRO 1. AUTO ===
	LDA #15 \ STA OPP_EXP_T \ LDY BULLET_Y \ LDA #0 \ STA $4180,Y \ STA BULLET_Y \ LDA #30 \ STA EXP_SND_T 
	SED
	CLC
	LDA SCORE
	ADC #1
	STA SCORE
	BCC _O1_NOC
	LDA SCORE_HI
	ADC #0
	STA SCORE_HI
_O1_NOC
	CLD 

_O1_P_COL
	LDA JUMP_VAL \ CMP #5 \ BCS _DRAW_OPP 
	LDA OPP_Y \ CMP #70 \ BCC _DRAW_OPP 
	LDA OPP_X \ CMP #14 \ BCC _DRAW_OPP \ CMP #21 \ BCS _DRAW_OPP 
	JMP CRASH_SEQ 

_DRAW_OPP
	LDA OPP_Y \ STA OPP_CUR_Y \ LDA SAVMSC \ STA OPP_SCR_LO \ LDA SAVMSH \ STA OPP_SCR_HI
	LDX OPP_Y \ BEQ _SKIP_MUL
_MUL_LOOP
	CLC \ LDA OPP_SCR_LO \ ADC #40 \ STA OPP_SCR_LO \ BCC _NO_C \ INC OPP_SCR_HI
_NO_C
	DEX \ BNE _MUL_LOOP
_SKIP_MUL
	CLC \ LDA OPP_SCR_LO \ ADC OPP_X \ STA OPP_SCR_LO \ BCC _NO_C2 \ INC OPP_SCR_HI
_NO_C2
	LDX #0 \ LDY #0
_D_L1
	LDA OPP_EXP_T \ BEQ _O1_NORM \ JSR _RAND_EXP \ JMP _O1_NEXT
_O1_NORM
	LDA OPP_S0,X \ STA (OPP_SCR_LO),Y \ INY \ LDA OPP_S1,X \ STA (OPP_SCR_LO),Y \ INY \ LDA OPP_S2,X \ STA (OPP_SCR_LO),Y \ INY \ LDA OPP_S3,X \ STA (OPP_SCR_LO),Y \ DEY \ DEY \ DEY
_O1_NEXT
	CLC \ LDA OPP_SCR_LO \ ADC #40 \ STA OPP_SCR_LO \ BCC _NC1 \ INC OPP_SCR_HI
_NC1
	INX \ CPX #16 \ BNE _D_L1 
_O1_DONE
	JMP OPP2_ROUTINE

OPP2_ROUTINE
	LDA OPP2_Y \ BNE _O2_LOGIC \ DEC OPP2_WAIT \ BEQ _O2_SPAWN \ JMP _O2_DONE
_O2_SPAWN
	LDA #22 \ STA OPP2_Y
	LDA RANDOM \ CMP #85 \ BCC _L2 \ CMP #170 \ BCC _C2_SPAWN
	LDA #2 \ BNE _S2
_L2	LDA #0 \ BEQ _S2
_C2_SPAWN LDA #1 
_S2	STA OPP2_LANE
	LDA RANDOM \ AND #$3F \ ORA #$40 \ STA OPP2_WAIT \ JMP _O2_CALCX

_O2_LOGIC
	LDA OPP2_EXP_T \ BEQ _O2_MOVE \ DEC OPP2_EXP_T \ BNE _O2_CALCX
	LDA #0 \ STA OPP2_Y \ JMP _O2_DONE 
_O2_MOVE
	JSR CALC_SPEED
	CLC \ ADC OPP2_Y \ STA OPP2_Y
	LDA OPP2_Y \ CMP #45 \ BCC _S2_D 
	INC OPP2_Y \ LDA OPP2_Y \ CMP #75 \ BCC _S2_D \ INC OPP2_Y
_S2_D
	LDA OPP2_Y \ CMP #96 \ BCC _O2_CALCX \ LDA #0 \ STA OPP2_Y \ JMP _O2_DONE 
_O2_CALCX
	LDA TRACK_X \ LSR \ LSR \ SEC \ SBC #1 \ STA OPP2_X
	LDA OPP2_LANE \ CMP #1 \ BEQ _O2_X_DONE
	LDA OPP2_Y \ LSR \ LSR \ LSR \ STA TEMP_Y
	LDA OPP2_LANE \ CMP #0 \ BEQ _O2_LEFT
_O2_RIGHT
	LDA OPP2_X \ CLC \ ADC TEMP_Y \ STA OPP2_X \ JMP _O2_X_DONE
_O2_LEFT
	LDA OPP2_X \ SEC \ SBC TEMP_Y \ STA OPP2_X
_O2_X_DONE

	LDA OPP2_EXP_T \ BNE _O2_P_COL
	LDA BULLET_Y \ BEQ _O2_P_COL
	
	; ODPUŠTĚNÍ NÁRAZU (Rozšířený Hitbox) POUZE OD LEVELU 3
	SEC \ SBC OPP2_Y
	LDX CUR_LEVEL \ CPX #2 \ BCS _O2_WIDE_HIT
_O2_NORM_HIT
	CMP #26 \ BCC _O2_P_COL \ CMP #34 \ BCS _O2_P_COL \ JMP _O2_X_CHK
_O2_WIDE_HIT
	CMP #22 \ BCC _O2_P_COL \ CMP #38 \ BCS _O2_P_COL
_O2_X_CHK
	LDA OPP2_X \ CMP #16 \ BCC _O2_P_COL \ CMP #20 \ BCS _O2_P_COL
	
	; === TADY SE POČÍTÁ SKÓRE PRO 2. AUTO ===
	LDA #15 \ STA OPP2_EXP_T \ LDY BULLET_Y \ LDA #0 \ STA $4180,Y \ STA BULLET_Y \ LDA #30 \ STA EXP_SND_T 
	SED
	CLC
	LDA SCORE
	ADC #1
	STA SCORE
	BCC _O2_NOC
	LDA SCORE_HI
	ADC #0
	STA SCORE_HI
_O2_NOC
	CLD 

_O2_P_COL
	LDA JUMP_VAL \ CMP #5 \ BCS _DRAW_OPP2
	LDA OPP2_Y \ CMP #70 \ BCC _DRAW_OPP2 
	LDA OPP2_X \ CMP #14 \ BCC _DRAW_OPP2 \ CMP #21 \ BCS _DRAW_OPP2
	JMP CRASH_SEQ 

_DRAW_OPP2
	LDA OPP2_Y \ STA OPP2_CUR_Y \ LDA SAVMSC \ STA OPP_SCR_LO \ LDA SAVMSH \ STA OPP_SCR_HI
	LDX OPP2_Y \ BEQ _SKIP_MUL2
_MUL_LOOP2
	CLC \ LDA OPP_SCR_LO \ ADC #40 \ STA OPP_SCR_LO \ BCC _NC2 \ INC OPP_SCR_HI
_NC2
	DEX \ BNE _MUL_LOOP2
_SKIP_MUL2
	CLC \ LDA OPP_SCR_LO \ ADC OPP2_X \ STA OPP_SCR_LO \ BCC _NC3 \ INC OPP_SCR_HI
_NC3
	LDX #0 \ LDY #0
_D_L2
	LDA OPP2_EXP_T \ BEQ _O2_NORM \ JSR _RAND_EXP \ JMP _O2_NEXT
_O2_NORM
	LDA OPP_S0,X \ STA (OPP_SCR_LO),Y \ INY \ LDA OPP_S1,X \ STA (OPP_SCR_LO),Y \ INY \ LDA OPP_S2,X \ STA (OPP_SCR_LO),Y \ INY \ LDA OPP_S3,X \ STA (OPP_SCR_LO),Y \ DEY \ DEY \ DEY
_O2_NEXT
	CLC \ LDA OPP_SCR_LO \ ADC #40 \ STA OPP_SCR_LO \ BCC _NC4 \ INC OPP_SCR_HI
_NC4
	INX \ CPX #16 \ BNE _D_L2
_O2_DONE
	JMP MAIN_LOOP

; ==============================================================================
; KONCOVÉ OBRAZOVKY (GAME OVER / VÍTĚZSTVÍ)
; ==============================================================================

CRASH_SEQ
	LDA #0 \ STA AUDC2 \ STA AUDC3 \ STA AUDC4 
	
	; OPRAVA TEČKY: OKAMŽITĚ SKRYJE STŘELU (MISSILE 0)!
	STA BULLET_Y
	STA HPOSM0
	
	LDA #100 \ STA PLAYER_EXP_T                
_CR_LOOP
	LDA RTCLOK
_CR_WAIT
	CMP RTCLOK
	BEQ _CR_WAIT
	
	LDX #16 \ LDA #96 \ SEC \ SBC JUMP_VAL \ TAY
_CR_P_L
	LDA RANDOM \ STA $4200,Y \ EOR #$FF \ STA $4280,Y 
	LDA RTCLOK \ STA $4300,Y \ EOR RANDOM \ STA $4380,Y 
	INY \ DEX \ BNE _CR_P_L

	LDA RANDOM \ STA $02C8 \ STA $02C4 \ STA $02C5
	LDA RANDOM \ STA AUDF1 \ LDA #$88 \ STA AUDC1
	
	DEC PLAYER_EXP_T \ BNE _CR_LOOP

	LDA #0 \ STA AUDC1 \ STA SDMCTL \ STA DMACTL  
	LDA #50 \ STA PLAYER_EXP_T
_CR_PAUSE
	LDA RTCLOK
_CR_P_WAIT
	CMP RTCLOK \ BEQ _CR_P_WAIT
	DEC PLAYER_EXP_T \ BNE _CR_PAUSE
	JMP GO_LOSE_SEQ


; --- SEKVENCE VÝHRY S POHÁREM ---
GO_WIN_SEQ
	; Nastavení radostné skladby
	LDA #<SONG_WIN \ STA END_S_LO \ LDA #>SONG_WIN \ STA END_S_HI

	LDA SCORE_HI \ AND #$0F \ ORA #$10 \ STA TXT_WIN2+28
	LDA SCORE \ LSR \ LSR \ LSR \ LSR \ ORA #$10 \ STA TXT_WIN2+29
	LDA SCORE \ AND #$0F \ ORA #$10 \ STA TXT_WIN2+30
	LDA #<DL_WIN \ STA SDLSTL \ STA DLIST \ LDA #>DL_WIN \ STA SDLSTH \ STA DLIST+1
	
	; OPRAVA - BEZPEČNÉ VYČIŠTĚNÍ PAMĚTI (Přesně 128 bytů per hráč)
	LDY #0 \ TYA
_CW_PM	STA $4200,Y \ STA $4280,Y \ STA $4300,Y \ STA $4380,Y \ INY \ CPY #128 \ BNE _CW_PM
	LDX #27
	; OPRAVA: POHÁR POSUNUT DOLŮ NA OFFSET $58
_DW_TR	LDA TROPHY_L,X \ STA $4258,X \ LDA TROPHY_R,X \ STA $42D8,X \ DEX \ BPL _DW_TR
	
	LDA #$1A \ STA COLP0 \ STA COLP1 
	LDA #$10 \ STA TEMP_Y            
	JMP GO_WAIT


; --- SEKVENCE PROHRY S LEBKOU ---
GO_LOSE_SEQ
	; Nastavení smutného umíráčku
	LDA #<SONG_LOSE \ STA END_S_LO \ LDA #>SONG_LOSE \ STA END_S_HI

	; ZOBRAZIT SKÓRE (ZNIČENÉ NEPŘÁTELE) I PŘI PROHŘE PRO 3 ČÍSLICE!
	LDA SCORE_HI \ AND #$0F \ ORA #$10 \ STA TXT_LOSE2+28
	LDA SCORE \ LSR \ LSR \ LSR \ LSR \ ORA #$10 \ STA TXT_LOSE2+29
	LDA SCORE \ AND #$0F \ ORA #$10 \ STA TXT_LOSE2+30

	LDA #<DL_LOSE \ STA SDLSTL \ STA DLIST \ LDA #>DL_LOSE \ STA SDLSTH \ STA DLIST+1

	; OPRAVA - BEZPEČNÉ VYČIŠTĚNÍ PAMĚTI (Přesně 128 bytů per hráč)
	LDY #0 \ TYA
_CL_PM	STA $4200,Y \ STA $4280,Y \ STA $4300,Y \ STA $4380,Y \ INY \ CPY #128 \ BNE _CL_PM
	LDX #29
	; OPRAVA: LEBKA POSUNUTA DOLŮ NA OFFSET $58
_DL_SK	LDA SKULL_L,X \ STA $4258,X \ LDA SKULL_R,X \ STA $42D8,X \ DEX \ BPL _DL_SK

	LDA #$44 \ STA COLP0 \ STA COLP1 
	LDA #$30 \ STA TEMP_Y            


; --- SPOLEČNÁ ČEKACÍ A BLIKACÍ SMYČKA S HUDBOU ---
GO_WAIT
	LDA #0 \ STA SONG_PTR \ STA SONG_TICK
	LDA #$03 \ STA SIZEP0 \ STA SIZEP1 
	LDA #96 \ STA HPOSP0 \ LDA #128 \ STA HPOSP1 
	
	LDA #0 \ STA AUDC1 \ STA AUDC2 \ STA AUDC3 \ STA AUDC4
	
	LDA #$2E \ STA DMACTL \ STA SDMCTL
	LDA #3 \ STA GRACTL  
	LDA #$E0 \ STA CHBASE \ LDA #$0F \ STA COLPF1 \ STA $02C4 \ STA $02C5
	LDA #$00 \ STA COLBK \ STA COLPF2 \ STA $02C6

_GW_REL
	LDA CONSOL \ AND #1 \ BEQ _GW_REL   

_GW_PRS
	; --- Synchronizace a Hudební Přehrávač ---
	LDA RTCLOK
_GW_SYNC
	CMP RTCLOK
	BEQ _GW_SYNC

	LDA SONG_TICK
	BEQ _GW_NEXT_NOTE
	DEC SONG_TICK
	JMP _GW_MUS_DONE

_GW_NEXT_NOTE
	LDA #6 ; Rychlost not v end screenu (1 nota = 6 snímků)
	STA SONG_TICK
	LDY SONG_PTR
	LDA (END_S_LO),Y
	STA AUDF1
	BEQ _GW_MUTE
	LDA #$A8 \ STA AUDC1 ; Zvuk čistého tónu
	JMP _GW_INC_PTR
_GW_MUTE
	LDA #0 \ STA AUDC1
_GW_INC_PTR
	INC SONG_PTR
	LDA SONG_PTR
	CMP #32
	BCC _GW_MUS_DONE
	LDA #0 \ STA SONG_PTR ; Opakování skladby

_GW_MUS_DONE
	; --- Blikání Barviček ---
	LDA RTCLOK \ AND #$10 \ BEQ _GW_C1
	LDA #$0F \ BNE _GW_C2
_GW_C1	LDA #$04
_GW_C2	STA $02C5

	LDA RTCLOK
	LSR \ LSR
	TAX
	AND #$0F
	STA ROW_CNT      
	TXA
	AND #$10         
	BEQ _GW_UP
	LDA #$0F
	SEC
	SBC ROW_CNT
	STA ROW_CNT      
_GW_UP
	LDA ROW_CNT
	ORA TEMP_Y       
	STA $02C8        
	STA $02C6        

	; --- Kontrola Tlačítka s přechodem do HIGH SCORE ---
	LDA CONSOL \ AND #1 \ BNE _GW_PRS   
_GW_REL2
	LDA CONSOL \ AND #1 \ BEQ _GW_REL2  
	
	; CHECK 2-BYTE HIGH SCORE ZDE!
	LDA SCORE_HI
	CMP HI_SCORE_HI
	BCC _NO_NEW_HI
	BNE _DO_NEW_HI
	LDA SCORE
	CMP HI_SCORE
	BCC _NO_NEW_HI
	BEQ _NO_NEW_HI
_DO_NEW_HI
	JMP NEW_HI_SEQ
_NO_NEW_HI
	JMP INTRO_START                     

; ==============================================================================
; ZÁPIS HIGH SCORE A PÍSMEN JAKO Z MARINGOTKY
; ==============================================================================
NEW_HI_SEQ
	LDA #0 \ STA AUDC1 \ STA AUDC2 \ STA AUDC3 \ STA AUDC4
	STA GRACTL \ STA HPOSM0 ; Vypne PMG a střelu
	
	LDA #$22 \ STA DMACTL \ STA SDMCTL ; Klasické zobrazení textu bez PMG
	LDA #<DL_HISCORE \ STA SDLSTL \ STA DLIST
	LDA #>DL_HISCORE \ STA SDLSTH \ STA DLIST+1
	
	; Vynulovat písmena na A A A (ATASCII hodnota $21)
	LDA #$21 \ STA TXT_CHARS+18 \ STA TXT_CHARS+20 \ STA TXT_CHARS+22
	
	LDA #0 \ STA CURSOR_POS
	LDA #20 \ STA JOY_DELAY

_HI_LOOP
	LDA RTCLOK \ _H_W: CMP RTCLOK \ BEQ _H_W
	
	; Disco barvičky na pozadí!
	LDA RTCLOK \ STA $02C4 \ STA $02C5
	
	; Smazat inverzi všech znaků pro čistý blik
	LDA TXT_CHARS+18 \ AND #$7F \ STA TXT_CHARS+18
	LDA TXT_CHARS+20 \ AND #$7F \ STA TXT_CHARS+20
	LDA TXT_CHARS+22 \ AND #$7F \ STA TXT_CHARS+22
	
	; Blikání aktuálního písmene (Inverzní zobrazení)
	LDA RTCLOK \ AND #$08 \ BEQ _H_NOB
	LDX CURSOR_POS
	LDA TXT_CHARS+18,X \ ORA #$80 \ STA TXT_CHARS+18,X
_H_NOB
	LDA JOY_DELAY \ BEQ _H_JOY
	DEC JOY_DELAY \ JMP _HI_LOOP

_H_JOY
	LDA PORTA \ AND #$01 \ BNE _H_DN
	; SMĚR NAHORU (Další písmeno)
	LDX CURSOR_POS
	LDA TXT_CHARS+18,X \ AND #$7F
	CLC \ ADC #1
	CMP #$3B \ BCC _H_SU \ LDA #$21 ; Z->A
_H_SU
	STA TXT_CHARS+18,X
	LDA #$A8 \ STA AUDC1 \ LDA #40 \ STA AUDF1 ; Pípnutí
	LDA #12 \ STA JOY_DELAY \ JMP _HI_LOOP
	
_H_DN
	LDA PORTA \ AND #$02 \ BNE _H_FIRE
	; SMĚR DOLŮ (Předchozí písmeno)
	LDX CURSOR_POS
	LDA TXT_CHARS+18,X \ AND #$7F
	SEC \ SBC #1
	CMP #$20 \ BNE _H_SD \ LDA #$3A ; A->Z
_H_SD
	STA TXT_CHARS+18,X
	LDA #$A8 \ STA AUDC1 \ LDA #40 \ STA AUDF1 ; Pípnutí
	LDA #12 \ STA JOY_DELAY \ JMP _HI_LOOP

_H_FIRE
	LDA #0 \ STA AUDC1 ; Vypnout zvuk
	LDA TRIG0 \ BEQ _H_CONFIRM
	LDA PORTA \ AND #$08 \ BEQ _H_CONFIRM ; I směr doprava potvrdí písmeno
	JMP _HI_LOOP
	
_H_CONFIRM
	; Potvrzení písmene doprava nebo Firem!
	LDX CURSOR_POS
	LDA TXT_CHARS+18,X \ AND #$7F \ STA TXT_CHARS+18,X ; Zruš inverzi
	
	LDA #$AF \ STA AUDC1 \ LDA #80 \ STA AUDF1 ; Zvuk potvrzení
	LDA #25 \ STA JOY_DELAY
	INC CURSOR_POS \ INC CURSOR_POS
	LDA CURSOR_POS \ CMP #6 \ BCS _H_SAVESCORE
	JMP _HI_LOOP
_H_SAVESCORE
	; OPRAVENÉ ZAPISOVÁNÍ A OFFSETY PRO 3 ČÍSLICE (STOVKY)
	LDA SCORE \ STA HI_SCORE
	LDA SCORE_HI \ STA HI_SCORE_HI
	
	LDA SCORE_HI \ AND #$0F \ ORA #$10 \ STA TXT_HISCR+21
	LDA SCORE \ LSR \ LSR \ LSR \ LSR \ ORA #$10 \ STA TXT_HISCR+22
	LDA SCORE \ AND #$0F \ ORA #$10 \ STA TXT_HISCR+23
	
	LDA TXT_CHARS+18 \ STA TXT_HISCR+27
	LDA TXT_CHARS+20 \ STA TXT_HISCR+28
	LDA TXT_CHARS+22 \ STA TXT_HISCR+29

	JMP INTRO_START

_RAND_EXP
	CPX #4 \ BCC _EXP_SML
	CPX #12 \ BCS _EXP_SML
	LDA RANDOM \ STA (OPP_SCR_LO),Y \ INY
	LDA RANDOM \ STA (OPP_SCR_LO),Y \ INY
	LDA RANDOM \ STA (OPP_SCR_LO),Y \ INY
	LDA RANDOM \ STA (OPP_SCR_LO),Y \ DEY \ DEY \ DEY \ RTS
_EXP_SML
	INY
	LDA RANDOM \ STA (OPP_SCR_LO),Y \ INY
	LDA RANDOM \ STA (OPP_SCR_LO),Y \ DEY \ DEY \ RTS

; --- SUBRUTINA PRO ČTVRTINOVÉ ZRYCHLOVÁNÍ ---
CALC_SPEED
	LDA RTCLOK
	AND #3
	ASL
	ASL
	CLC
	ADC CUR_LEVEL
	TAX
	LDA TAB_SPEED,X
	RTS

; ==============================================================================
; DATA POZADÍ, SPRITŮ A HUDBY
; ==============================================================================

; Zlomková tabulka rychlostí pro 10 levelů (40 hodnot)
TAB_SPEED   dta b(1,1,2,2, 1,2,2,3, 1,1,1,2, 1,2,2,2, 2,2,3,3)
            dta b(2,3,3,3, 2,3,3,4, 2,2,3,3, 3,3,4,4, 3,4,4,4)
MUSIC_SPEED dta b(128,152,180,210,240, 250,250,250,250,250)

; Hrdinská Vítězná Fanfára (Stoupající tóny)
SONG_WIN  dta b(121,121, 0,0, 81,81, 0,0, 60,60, 0,0, 47,47, 0,0)
          dta b(40,40,40,40, 40,40,40,40, 0,0,0,0, 0,0,0,0)

; Smutný Umíráček (Depresivní klesající tóny)
SONG_LOSE dta b(121,121,121,121, 162,162,162,162, 193,193,193,193, 243,243,243,243)
          dta b(243,243,243,243, 0,0,0,0, 0,0,0,0, 0,0,0,0)

; --- SPRITE DATA PRO GAME OVER / WIN OBRAZOVKY ---
TROPHY_L dta b($3F,$3F,$7F,$7F,$FF,$FF,$FF,$FF,$7F,$7F,$3F,$3F,$0F,$0F,$07,$07,$03,$03,$03,$03,$03,$03,$0F,$0F,$3F,$3F,$3F,$3F)
TROPHY_R dta b($FC,$FC,$FE,$FE,$FF,$FF,$FF,$FF,$FE,$FE,$FC,$FC,$F0,$F0,$E0,$E0,$C0,$C0,$C0,$C0,$C0,$C0,$F0,$F0,$FC,$FC,$FC,$FC)
SKULL_L  dta b($0F,$0F,$3F,$3F,$7F,$7F,$73,$73,$73,$73,$7F,$7F,$3F,$3F,$15,$15,$1F,$1F,$00,$00,$61,$61,$33,$33,$1E,$1E,$33,$33,$61,$61)
SKULL_R  dta b($F0,$F0,$FC,$FC,$FE,$FE,$CE,$CE,$CE,$CE,$FE,$FE,$FC,$FC,$A8,$A8,$F8,$F8,$00,$00,$86,$86,$CC,$CC,$78,$78,$CC,$CC,$86,$86)

CITY_LO dta l(CITY_R1,CITY_R2,CITY_R3,CITY_R4,CITY_R5,CITY_R6,CITY_R7,CITY_R8,CITY_R9,CITY_R10,CITY_R11,CITY_R12)
CITY_HI dta h(CITY_R1,CITY_R2,CITY_R3,CITY_R4,CITY_R5,CITY_R6,CITY_R7,CITY_R8,CITY_R9,CITY_R10,CITY_R11,CITY_R12)
HILLS_LO dta l(HILLS_R1,HILLS_R2,HILLS_R3,HILLS_R4,HILLS_R5,HILLS_R6,HILLS_R7,HILLS_R8,HILLS_R9,HILLS_R10,HILLS_R11,HILLS_R12)
HILLS_HI dta h(HILLS_R1,HILLS_R2,HILLS_R3,HILLS_R4,HILLS_R5,HILLS_R6,HILLS_R7,HILLS_R8,HILLS_R9,HILLS_R10,HILLS_R11,HILLS_R12)
WINTER_LO dta l(WINTER_R1,WINTER_R2,WINTER_R3,WINTER_R4,WINTER_R5,WINTER_R6,WINTER_R7,WINTER_R8,WINTER_R9,WINTER_R10,WINTER_R11,WINTER_R12)
WINTER_HI dta h(WINTER_R1,WINTER_R2,WINTER_R3,WINTER_R4,WINTER_R5,WINTER_R6,WINTER_R7,WINTER_R8,WINTER_R9,WINTER_R10,WINTER_R11,WINTER_R12)

HILLS_R12 dta b($FF,$FF,$FF,$FF,$FF,$FF,$FF,$AA,$AA,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$AA,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$AA,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF)
HILLS_R11 dta b($FF,$FF,$FF,$FF,$FF,$AA,$AA,$AA,$AA,$AA,$FF,$FF,$FF,$FF,$FF,$AA,$AA,$AA,$FF,$FF,$FF,$FF,$FF,$FF,$AA,$AA,$AA,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF)
HILLS_R10 dta b($FF,$FF,$FF,$AA,$AA,$AA,$AA,$55,$AA,$AA,$AA,$FF,$FF,$FF,$AA,$AA,$AA,$AA,$AA,$FF,$FF,$FF,$FF,$AA,$AA,$AA,$AA,$AA,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF)
HILLS_R9 dta b($FF,$FF,$AA,$AA,$AA,$55,$55,$55,$55,$AA,$AA,$AA,$AA,$AA,$AA,$55,$55,$AA,$AA,$AA,$FF,$FF,$AA,$AA,$55,$55,$AA,$AA,$AA,$AA,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF)
HILLS_R8 dta b($FF,$AA,$AA,$55,$55,$55,$55,$FF,$55,$55,$AA,$AA,$AA,$55,$55,$55,$55,$55,$AA,$AA,$FF,$AA,$55,$55,$55,$55,$55,$AA,$AA,$AA,$AA,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF)
HILLS_R7 dta b($AA,$AA,$55,$55,$55,$55,$FF,$FF,$FF,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$AA,$AA,$55,$55,$55,$55,$55,$55,$55,$AA,$AA,$AA,$AA,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF)
HILLS_R6 dta b($AA,$55,$55,$55,$55,$FF,$FF,$FF,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$AA,$AA,$AA,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF)
HILLS_R5 dta b($55,$55,$55,$55,$55,$FF,$FF,$FF,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$AA,$AA,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF)
HILLS_R4 dta b($55,$55,$55,$55,$55,$55,$FF,$FF,$FF,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$AA,$AA,$FF,$FF,$FF,$FF,$FF,$FF,$FF)
HILLS_R3 dta b($55,$55,$55,$55,$55,$55,$55,$FF,$FF,$FF,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$AA,$AA,$FF,$FF,$FF,$FF,$FF,$FF)
HILLS_R2 dta b($55,$55,$55,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$AA,$AA,$FF,$FF,$FF,$FF,$FF)
HILLS_R1 dta b($55,$55,$55,$55,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$AA,$AA,$FF,$FF,$FF,$FF)

CITY_R12 dta b($FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$EE,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$EE,$FF,$FF)
CITY_R11 dta b($FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$BB,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$BB,$FF,$FF)
CITY_R10 dta b($FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$AA,$AA,$AA,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$AA,$AA,$AA,$FF)
CITY_R9 dta b($FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$BB,$BB,$BB,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$BB,$BB,$BB,$FF)
CITY_R8 dta b($FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$AA,$AA,$FF,$FF,$FF,$AA,$EE,$EE,$EE,$AA,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$AA,$AA,$FF,$FF,$FF,$AA,$EE,$EE,$EE,$AA)
CITY_R7 dta b($FF,$FF,$FF,$FF,$AA,$AA,$FF,$FF,$FF,$AA,$77,$77,$AA,$FF,$FF,$BB,$BB,$BB,$BB,$BB,$FF,$FF,$FF,$FF,$AA,$AA,$FF,$FF,$FF,$AA,$77,$77,$AA,$FF,$FF,$BB,$BB,$BB,$BB,$BB)
CITY_R6 dta b($FF,$FF,$FF,$AA,$BB,$BB,$AA,$FF,$AA,$DD,$DD,$DD,$DD,$AA,$FF,$EE,$EE,$EE,$EE,$EE,$FF,$FF,$FF,$AA,$BB,$BB,$AA,$FF,$AA,$DD,$DD,$DD,$DD,$AA,$FF,$EE,$EE,$EE,$EE,$EE)
CITY_R5 dta b($FF,$FF,$AA,$EE,$EE,$EE,$EE,$AA,$AA,$77,$77,$77,$77,$77,$AA,$BB,$BB,$BB,$BB,$BB,$FF,$FF,$AA,$EE,$EE,$EE,$EE,$AA,$AA,$77,$77,$77,$77,$77,$AA,$BB,$BB,$BB,$BB,$BB)
CITY_R4 dta b($FF,$AA,$BB,$BB,$BB,$BB,$BB,$BB,$AA,$DD,$DD,$DD,$DD,$DD,$DD,$EE,$EE,$EE,$EE,$EE,$FF,$AA,$BB,$BB,$BB,$BB,$BB,$BB,$AA,$DD,$DD,$DD,$DD,$DD,$DD,$EE,$EE,$EE,$EE,$EE)
CITY_R3 dta b($AA,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$AA,$77,$77,$77,$77,$77,$77,$BB,$BB,$BB,$BB,$BB,$AA,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$AA,$77,$77,$77,$77,$77,$77,$BB,$BB,$BB,$BB,$BB)
CITY_R2 dta b($BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$DD,$DD,$DD,$DD,$DD,$DD,$EE,$EE,$EE,$EE,$EE,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$DD,$DD,$DD,$DD,$DD,$DD,$EE,$EE,$EE,$EE,$EE)
CITY_R1 dta b($EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$77,$77,$77,$77,$77,$77,$BB,$BB,$BB,$BB,$BB,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$77,$77,$77,$77,$77,$77,$BB,$BB,$BB,$BB,$BB)

WINTER_R12 dta b($FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$00,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$00,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$00,$FF,$FF,$FF,$FF,$FF)
WINTER_R11 dta b($FF,$FF,$FF,$FF,$FF,$FF,$FF,$00,$00,$00,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$00,$00,$00,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$00,$00,$00,$FF,$FF,$FF,$FF)
WINTER_R10 dta b($FF,$FF,$FF,$FF,$FF,$FF,$00,$00,$55,$00,$00,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$00,$00,$55,$00,$00,$FF,$FF,$FF,$FF,$FF,$00,$00,$55,$00,$00,$FF,$FF,$FF)
WINTER_R9  dta b($FF,$FF,$FF,$FF,$FF,$00,$00,$55,$55,$55,$00,$00,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$00,$00,$55,$55,$55,$00,$00,$FF,$FF,$FF,$00,$00,$55,$55,$55,$00,$00,$FF,$FF)
WINTER_R8  dta b($FF,$FF,$FF,$FF,$00,$00,$55,$55,$55,$55,$55,$00,$00,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$00,$00,$55,$55,$55,$55,$55,$00,$00,$FF,$00,$00,$55,$55,$55,$55,$55,$00,$00,$FF)
WINTER_R7  dta b($FF,$FF,$FF,$00,$00,$55,$55,$55,$AA,$AA,$55,$55,$00,$00,$FF,$FF,$FF,$FF,$FF,$00,$00,$55,$55,$55,$AA,$AA,$55,$55,$00,$00,$55,$55,$55,$AA,$AA,$55,$55,$00,$00,$AA)
WINTER_R6  dta b($FF,$FF,$00,$00,$55,$55,$55,$AA,$AA,$AA,$AA,$55,$55,$00,$00,$FF,$FF,$FF,$00,$00,$55,$55,$55,$AA,$AA,$AA,$AA,$55,$55,$00,$00,$55,$AA,$AA,$AA,$AA,$55,$00,$00,$AA)
WINTER_R5  dta b($FF,$00,$00,$55,$55,$55,$AA,$AA,$AA,$AA,$AA,$AA,$55,$55,$00,$00,$FF,$00,$00,$55,$55,$55,$AA,$AA,$AA,$AA,$AA,$AA,$55,$55,$00,$00,$AA,$AA,$AA,$AA,$AA,$55,$00,$00)
WINTER_R4  dta b($00,$00,$55,$55,$55,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$55,$55,$00,$00,$55,$55,$55,$55,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$55,$55,$00,$AA,$AA,$AA,$AA,$AA,$55,$55,$00)
WINTER_R3  dta b($00,$55,$55,$55,$55,$55,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$55,$55,$55,$55,$55,$55,$55,$55,$55,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$55,$55,$55,$AA,$AA,$AA,$AA,$AA,$55,$55,$55)
WINTER_R2  dta b($55,$55,$55,$55,$55,$55,$55,$AA,$AA,$AA,$AA,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$AA,$AA,$AA,$AA,$55,$55,$55,$55,$55,$55,$AA,$AA,$AA,$AA,$55,$55,$55)
WINTER_R1  dta b($55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55)

OPP_S0 dta b($00,$01,$00,$3F,$3F,$00,$00,$05,$05,$05,$00,$FF,$FF,$FF,$00,$00)
OPP_S1 dta b($15,$55,$05,$05,$05,$15,$5A,$55,$55,$55,$55,$55,$55,$15,$00,$00)
OPP_S2 dta b($54,$55,$50,$50,$50,$54,$A5,$55,$55,$55,$55,$55,$55,$54,$00,$00)
OPP_S3 dta b($00,$40,$00,$FC,$FC,$00,$00,$50,$50,$50,$00,$FF,$FF,$FF,$00,$00)

HOLE_S0 dta b(0,0,0,0,0,0,0,0,0,0,0,$00,$0A,$AA,$AA,$0A)
HOLE_S1 dta b(0,0,0,0,0,0,0,0,0,0,0,$0A,$AA,$AA,$AA,$A8)
HOLE_S2 dta b(0,0,0,0,0,0,0,0,0,0,0,$2A,$AA,$AA,$AA,$A8)
HOLE_S3 dta b(0,0,0,0,0,0,0,0,0,0,0,$00,$A0,$AA,$AA,$0A)

TREE_S0 dta b($03,$0F,$3F,$0F,$3F,$FF,$03,$03)
TREE_S1 dta b($C0,$F0,$FC,$F0,$FC,$FF,$C0,$C0)

CAR_LEFT dta b($1F,$3F,$03,$03,$07,$07,$1F,$38,$38,$1F,$0F,$0F,$0F,$0F,$00,$00,$3F,$7F,$07,$07,$0F,$0F,$3F,$70,$70,$3F,$1F,$1F,$1F,$1F,$00,$00,$0F,$1F,$01,$01,$03,$03,$0F,$1C,$1C,$0F,$07,$07,$07,$07,$00,$00)
CAR_RIGHT dta b($F8,$FC,$C0,$C0,$E0,$E0,$F8,$1C,$1C,$F8,$F0,$F0,$F0,$F0,$00,$00,$F0,$F8,$80,$80,$C0,$C0,$F0,$38,$38,$F0,$E0,$E0,$E0,$E0,$00,$00,$FC,$FE,$E0,$E0,$F0,$F0,$FC,$0E,$0E,$FC,$F8,$F8,$F8,$F8,$00,$00)
TIRE_LEFT dta b($00,$00,$E0,$E0,$E0,$00,$00,$00,$00,$00,$F0,$F0,$F0,$F0,$00,$00,$00,$00,$E0,$E0,$E0,$00,$00,$00,$00,$00,$E0,$E0,$E0,$E0,$00,$00,$00,$00,$E0,$E0,$E0,$00,$00,$00,$00,$00,$F8,$F8,$F8,$F8,$00,$00)
TIRE_RIGHT dta b($00,$00,$07,$07,$07,$00,$00,$00,$00,$00,$0F,$0F,$0F,$0F,$00,$00,$00,$00,$07,$07,$07,$00,$00,$00,$00,$00,$07,$07,$07,$07,$00,$00,$00,$00,$07,$07,$07,$00,$00,$00,$00,$00,$1F,$1F,$1F,$1F,$00,$00)

SONG_TAB dta b($AD,$AD,0,0,$AD,$AD,0,0,$AD,$AD,0,0,$AD,$AD,0,0,0,0,0,0,$AD,0,$88,0,$7C,0,$6C,0,$AD,0,$88,0)
SIN_TAB dta b(24,24,24,25,25,25,26,26,26,26,26,26,25,25,25,24,24,24,23,23,23,22,22,22,21,21,21,21,21,21,22,22,22,23,23,23,24,24,24,25,25,25,26,26,25,25,24,24)

MASK_L_WHITE dta b($AA,$6A,$5A,$56)
MASK_L_BLACK dta b($00,$40,$50,$54)
MASK_R_WHITE dta b($95,$A5,$A9,$AA)
MASK_R_BLACK dta b($15,$05,$01,$00)

	RUN BOOT_START